# Generated by Django 3.2.25 on 2025-10-07 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(help_text='Discount percentage (1–100)')),
                ('deadline', models.DateField(default=profiles.models.default_deadline, help_text='Promotion expiration date')),
                ('active', models.BooleanField(default=False, help_text='Is the promotion currently active?')),
                ('validity', models.BooleanField(default=True, help_text='Is the promotion still valid?')),
                ('category', models.ForeignKey(help_text='Product category associated with this promotion.', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Value of the voucher in euros', max_digits=6)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase to apply voucher', max_digits=6)),
                ('deadline', models.DateField(default=profiles.models.default_deadline, help_text='Voucher expiration date')),
                ('active', models.BooleanField(default=False, help_text='Is the voucher active?')),
                ('validity', models.BooleanField(default=True, help_text='Is the voucher still valid?')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=django.utils.crypto.get_random_string, max_length=12, unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promotions', models.ManyToManyField(blank=True, to='profiles.Promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vouchers', models.ManyToManyField(blank=True, to='profiles.Voucher')),
            ],
        ),
    ]
