# Generated by Django 3.2.25 on 2025-10-09 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_promotion_subscription_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='vouchers',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 11, 8), help_text='Promotion expiration date'),
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
