# Generated by Django 3.2.25 on 2025-06-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='max_participants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
