# Generated by Django 3.2.25 on 2025-06-27 09:42

from django.db import migrations, models
import django.db.models.deletion
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20250624_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='max_participants',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='title',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=60)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(default='Untitled Class', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.fitnessclass'),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
    ]
