# Generated by Django 3.2.25 on 2025-06-27 09:47

import datetime
from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20250627_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=60)),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='instructor',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(default='Untitled Class', max_length=100),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
