# Generated by Django 3.2.25 on 2025-06-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20250627_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='name',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='max_participants',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fitness_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.fitnessclass'),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='instructor',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
