# Generated by Django 3.2.25 on 2025-06-27 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20250627_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
