# Generated by Django 3.2.25 on 2025-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20250627_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fitness_class',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='duration',
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='max_participants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
