# Generated by Django 3.2.25 on 2025-06-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20250627_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fitness_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.fitnessclass'),
            preserve_default=False,
        ),
    ]
