# Generated by Django 3.2.25 on 2025-10-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_booking_fitness_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={'verbose_name': 'Fitness Class', 'verbose_name_plural': 'Fitness Classes'},
        ),
    ]
